package xv.training.SpringbootRestapi.entities;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
public class Student {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) //auto will create hibernate sequence 
	long id;                                        //when student id,organization id will be autogenerated
	String name,sex,qualification;                  //it will not create error to organization/1 when student/1 is running
	int age;                                        //we can run both at a time so dats y we hav given identity
	
	@ManyToOne(fetch = FetchType.LAZY)  //lazy means it will generate when we need where as eager wil generate at dat time only.
	@JoinColumn(name = "organization")
	@JsonIgnore //student and organization will be in the infinite loop soo we shud ignore it
	private Organization organization;
	
	public Student( String name, String sex, String qualification, int age, Organization organization) {
		super();
		
		this.name = name;
		this.sex = sex;
		this.qualification = qualification;
		this.age = age;
		this.organization = organization;
	}

	public Student() {
		
	}
	
	
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getQualification() {
		return qualification;
	}
	public void setQualification(String qualification) {
		this.qualification = qualification;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}
	
	
}
